name: ar_widget
description: Widget in the AR World
version: 0.0.5
homepage: https://github.com/rbdog/flutter_note_packages

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math:
  json_annotation:
  permission_handler:
  arkit_plugin:
  plugin_platform_interface:

dev_dependencies:
  flutter_lints:

flutter:
  plugin:
    platforms:
      android:
        package: biz.rbdog.ar_widget
        pluginClass: ArWidgetPlugin
      ios:
        pluginClass: ArWidgetPlugin
