name: ar_widget
description: Widget in the AR World
version: 0.0.3
homepage: https://github.com/rbdog/flutter_note_packages

environment:
  sdk: ^3.0.0
  flutter: ">=3.3.0"

dependencies:
  vector_math: ^2.1.1
  json_annotation: ^4.5.0
  permission_handler: ^10.1.0
  arkit_plugin: ^1.0.6
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: biz.rbdog.ar_widget
        pluginClass: ArWidgetPlugin
      ios:
        pluginClass: ArWidgetPlugin
