name: virtual_phone
version: 0.4.0
description: A web-based smart phone simulator.
homepage: https://github.com/rbdog/flutter_note_packages

environment:
  sdk: ^3.0.0
  flutter: ^3.16.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation:
  json_annotation:
  shared_preferences:
  collection:
  flutter_riverpod:
  flutter_hooks:

dev_dependencies:
  flutter_lints:
  build_runner:
  freezed:
  json_serializable:

flutter:
  assets:
    - assets/images/
