name: ui_router
description: GoRouter Alternative, without context
version: 3.4.0
homepage: https://github.com/rbdog/flutter_note_packages

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
