name: go_router_express
description: An Express.js-like wrapper for go_router that provides a familiar routing API for Flutter applications.
version: 1.0.2
repository: https://github.com/rbdog/flutter_note_packages/tree/main/go_router_express
issue_tracker: https://github.com/rbdog/flutter_note_packages/issues

environment:
  sdk: ^3.9.0
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
