name: pixel_color_image
description: >
  Pick the pixel color of a image.
  onHover, onTap, and the Preview widget.
version: 1.2.2
homepage: https://github.com/rbdog/pixel_color_image
repository: https://github.com/rbdog/pixel_color_image

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
