name: pixel_color_image
description: >
  Pick the pixel color of a image.
  onHover, onTap, and the Preview widget.
version: 1.2.5
repository: https://github.com/rbdog/flutter_note_packages

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  http:
  image:

dev_dependencies:
  flutter_lints:

flutter:
