name: go_router_express_example
description: Example application demonstrating go_router_express usage.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter
  go_router_express:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
