name: liveroom
description: Super simple WebSocket Room kit
version: 1.1.0
repository: https://github.com/rbdog/flutter_note_packages

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  uuid:
  web_socket_channel:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints:
