name: liveroom_test
description: A new Flutter project.
version: 1.0.0

publish_to: "none"

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  liveroom:
    path: "../liveroom/liveroom"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
